# Generated by Django 3.1.6 on 2021-02-06 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_auto_20210206_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='own',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='total_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 6, 21, 10, 10, 93390), null=True),
        ),
    ]
