# Generated by Django 3.1.6 on 2021-02-06 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_auto_20210206_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='workerjobs', to='workers.Worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 6, 21, 11, 27, 248308), null=True),
        ),
    ]
