# Generated by Django 3.1.6 on 2021-02-06 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_auto_20210206_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 7, 0, 18, 40, 815352), null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='total_money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 7, 0, 18, 40, 814350), null=True),
        ),
    ]
