# Generated by Django 3.1.6 on 2021-02-06 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_auto_20210207_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 7, 0, 59, 18, 243581), null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='money',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='total_hours',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 7, 0, 59, 18, 242582), null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='own',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='total_hours',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='total_money',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
