# Generated by Django 3.1.6 on 2021-02-07 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0018_auto_20210207_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Money_For_Hour',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 7, 23, 50, 38, 973264), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 7, 23, 50, 38, 972261), null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 7, 23, 50, 38, 971224), null=True),
        ),
    ]
