# Generated by Django 3.1.6 on 2021-02-08 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0020_auto_20210207_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Money_For_Hour',
            field=models.FloatField(default=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 8, 15, 15, 39, 260350), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 8, 15, 15, 39, 259372), null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 8, 15, 15, 39, 259372), null=True),
        ),
    ]
