# Generated by Django 3.1.6 on 2021-02-08 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0021_auto_20210208_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('changehours', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 8, 15, 38, 47, 673116), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 8, 15, 38, 47, 672119), null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 8, 15, 38, 47, 671123), null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='jobchange',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobchange', to='workers.ChangeJob'),
        ),
    ]
