# Generated by Django 3.1.6 on 2021-02-08 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0023_auto_20210208_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changejob',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 8, 16, 6, 30, 910432), null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 8, 16, 6, 30, 909435), null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 8, 16, 6, 30, 908437), null=True),
        ),
    ]
